Repository MicrosoftDocs/winui-api, pull requests merged in 2023-01, with the labels that each got.

#130 add .openpublishing.publish.config.json for PR auto-assignment
  .openpublishing.publish.config.json
Labels: do-not-merge, review-team-triage

#132 Update microsoft_ui_xaml_xamltypeinfo.md
  microsoft.ui.xaml.xamltypeinfo/microsoft_ui_xaml_xamltypeinfo.md
Labels: Change sent to author, do-not-merge, reunion/prod, winui-reference/tech

#133 fix-yaml-in-config.json
  .openpublishing.publish.config.json
Labels: do-not-merge, review-team-triage

#131 Update colorpicker_isalphaenabled.md
  microsoft.ui.xaml.controls/colorpicker_isalphaenabled.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, reunion/prod, winui-reference/tech

#134 Update xamlcontrolsxamlmetadataprovider_initialize_1754723448.md
  microsoft.ui.xaml.xamltypeinfo/xamlcontrolsxamlmetadataprovider_initialize_1754723448.md
Labels: Change sent to author, do-not-merge, reunion/prod, winui-reference/tech

#136 Update expander.md
  microsoft.ui.xaml.controls/expander.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, reunion/prod, winui-reference/tech
